name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
          
      - name: Upload COS
        uses: Loskh/onedrive-action@v0.5
        with:
          file_name: test.bin
          file_path: .
          upload_path: /downloads/
          redirect_uri: "https://file.ffxiv.wang/"
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
