name: CI-TEST

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: main
          
      # - name: Upload OneDrive
      #   uses: Loskh/onedrive-action@master
      #   with:
      #     files: "*.bin"
      #     upload_path: /downloads/ci_test/
      #     redirect_uri: "https://file.ffxiv.wang/"
      #     client_id: ${{ secrets.CLIENT_ID }}
      #     client_secret: ${{ secrets.CLIENT_SECRET }}
      #     refresh_token: ${{ secrets.REFRESH_TOKEN }}

      - name: Upload OneDrive
        uses: Loskh/onedrive-action@master
        with:
          folder: foldertest
          upload_path: /downloads/ci_test/folder/
          redirect_uri: "https://file.ffxiv.wang/"
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
