# This is a basic workflow to help you get started with Actions

name: Release XL

on:
  workflow_dispatch:
  
jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
      - name: Download Release        
      - run: |
          $releases = Invoke-WebRequest -Uri 'https://api.github.com/repos/ottercorp/FFXIVQuickLauncher/releases'
          $current = ConvertFrom-Json -InputObject $releases.Content | Select-Object -First 1
          $refver = $env:GITHUB_REF -replace '.*/'
          echo "::set-output name=version::$refver"
          nuget pack .\XIVLauncher.nuspec -properties version=$refver
          mkdir Releases
          cp .\XIVLauncher\Resources\CHANGELOG.txt .\Releases\
          $release_file = $current.assets | Where-Object -Property name -Value RELEASES -EQ
          Invoke-WebRequest -Uri $release_file.browser_download_url -OutFile .\Releases\RELEASES
          $delta_file = $current.assets | Where-Object -Property name -Value "*delta.nupkg" -Like
          try
          {
            Invoke-WebRequest -Uri $delta_file.browser_download_url -OutFile ".\Releases\$($delta_file.name)"
          }
          catch
          {
          }
          $full_file = $current.assets | Where-Object -Property name -Value "*full.nupkg" -Like
          Invoke-WebRequest -Uri $full_file.browser_download_url -OutFile ".\Releases\$($full_file.name)"
          cd Releases
        shell: pwsh  
        
      - name: Upload OneDrive
        uses: Loskh/onedrive-action@v0.7
        with:
          files: "*"
          upload_path: /downloads/ci_test/
          redirect_uri: "https://file.ffxiv.wang/"
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}      
